server: 
   port: 8771
# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：  
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test  
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod  
## 刷新时，关闭安全验证
management: 
  security: 
     enabled: false
spring:
  profiles:  
    active: dev
  application: 
    name: conf-client    
  cloud:
    config:
      label: master
      name: conf
      profiles: pro
      uri: http://localhost:8770
  bus:  
    trace: 
      enabled: true      ## 开启消息跟踪
  rabbitmq: 
    host: localhost
    port: 5672
    username: cd
    password: 123456    

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/ 
        
        