server: 
   port: 8781
# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：  
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test  
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod  
spring:
  profiles:  
    active: dev
  application: 
    name: zipkinClient      
  zipkin: 
     base-url: http://localhost:9411
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/     